package com.fst.trainingcenter.services.Email;

public class EmailStyles {
    public static String getStyles() {
        return "<head>"
                + "<style>"
                + ".container {"
                + "  display: flex;"
                + "  flex-direction: column;"
                + "  align-items: center;"
                + "  justify-content: center;"
                + "  height: 100vh;"
                + "  font-family: Verdana, Geneva, Tahoma, sans-serif;"
                + "  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);"
                + "  border-radius: 5px;"
                + "  background-color: white;"
                + "  font-size: 15px;"
                + "  text-align: center;"
                + "  margin-right: 300px;"
                + "  margin-left: 300px;"
                + "}"
                + ".text-container {"
                + "  margin-top: 20px;"
                + "  padding: 20px;"
                + "  text-align: left;"
                + "}"
                + ".button-link {"
                + "  display: inline-block;"
                + "  padding: 10px 20px;"
                + "  background-color: #007bff;"
                + "  color: white;"
                + "  text-decoration: none;"
                + "  border-radius: 5px;"
                + "  text-align: center;"
                + "}"
                + ".button-link:hover {"
                + "  background-color: #82a4eb;"
                + "}"
                + ".social-icons {"
                + "  margin-top: 20px;"
                + "  text-align: center;"
                + "}"
                + ".ntt {"
                + "  margin-top: 30px;"
                + "  text-align: center;"
                + "}"
                + "a {"
                + "  color: #007bff;"
                + "  font-weight: bold;"
                + "}"
                + "span {"
                + "  color: #007bff;"
                + "  font-weight: bold;"
                + "}"
                + ".image-container {"
                + "  margin-right: 600px;"
                + "  margin-left: 300px;"
                + "  text-align: center;"
                + "}"
                + ".social-icons {"
                + "  margin-top: 30px;"
                + "  text-align: center;"
                + "}"
                + "</style>"
                + "<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css'>"
                + "</head>";
    }
}
