import API from "../API";
// Generated by https://quicktype.io

export interface EvaluationData {
    pedagogicalQuality: string;
    pace:               string;
    courseSupport:      string;
    subjectMastery:     string;
    code:               string;
    trainerId:          number;
    individualId:       number;
}

//General Header
const headers = {
    'Content-Type': 'application/json', // Example header, adjust as needed
};

//Save Evaluation

export const SaveEvaluation = (evaluationData: EvaluationData) => {

    return API.post(`/evaluations`, evaluationData , {headers})
    .then((res) => res)
    .catch((error) => {
        const errorMessage: string = error.response.data?.message || "Conflict error occurred.";
        throw new Error(errorMessage);        
    });

}
