package com.fst.trainingcenter.enums;



public enum Category {
    SOFTWARE_ENGINEERING,
    ARTIFICIAL_INTELLIGENCE,
    WEB_DEVELOPMENT,
    DATABASE_SYSTEMS,
    NETWORKING,
    MACHINE_LEARNING,
    SECURITY,
    DATA_SCIENCE,
    CLOUD_COMPUTING,
    MOBILE_APP_DEVELOPMENT;


}
